name: Deploy Project by Copying

on:
  push:
    branches:
      - main # или ваша ветка для деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Archive Project
        run: tar -czf project.tar.gz .

      - name: Copy Project to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "project.tar.gz"
          target: "/tmp"

      - name: Deploy Project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ vars.DEFAULT_PATH }}${{ vars.PROJECT_PATH }}
            tar -xzf /tmp/project.tar.gz -C .
            export MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            export MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            export MYSQL_USER=${{ secrets.MYSQL_USER }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
